export const ERROR_CODES = Object.freeze({
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_NOT_HEALTHY: "ACCOUNT_NOT_HEALTHY",
  API_FAILED: "API_FAILED",
  BOUNDARY_NOT_REACHED: "BOUNDARY_NOT_REACHED",
  CHALLENGE_REQUIRED: "CHALLENGE_REQUIRED",
  CHRONOLOGY_UNVERIFIED: "CHRONOLOGY_UNVERIFIED",
  CONFIG_INVALID: "CONFIG_INVALID",
  DUPLICATE_SOURCE_JOB: "DUPLICATE_SOURCE_JOB",
  GROUP_ACCESS_LOST: "GROUP_ACCESS_LOST",
  GROUP_DELETED: "GROUP_DELETED",
  GROUP_UNAVAILABLE: "GROUP_UNAVAILABLE",
  JOB_EXPIRED: "JOB_EXPIRED",
  JOB_INVALID: "JOB_INVALID",
  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  OVERLAPPING_RUN: "OVERLAPPING_RUN",
  POST_EXTRACTION_FAILED: "POST_EXTRACTION_FAILED",
  PROXY_AUTH_FAILED: "PROXY_AUTH_FAILED",
  PROXY_FAILED: "PROXY_FAILED",
  PROXY_IDENTITY_SAVE_FAILED: "PROXY_IDENTITY_SAVE_FAILED",
  PROXY_ROTATED: "PROXY_ROTATED",
  RESERVATION_TOO_LOW: "RESERVATION_TOO_LOW",
  RESULT_PAYLOAD_TOO_LARGE: "RESULT_PAYLOAD_TOO_LARGE",
  SESSION_SAVE_FAILED: "SESSION_SAVE_FAILED",
  SESSION_MISSING: "SESSION_MISSING",
  TIMESTAMP_UNVERIFIED: "TIMESTAMP_UNVERIFIED",
  TRANSFER_LIMIT_EXCEEDED: "TRANSFER_LIMIT_EXCEEDED",
  WORKER_ERROR: "WORKER_ERROR"
});

export class ScraperError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "ScraperError";
    this.code = code;
    this.details = details;
  }
}

export function asScraperError(error, fallbackCode = ERROR_CODES.WORKER_ERROR) {
  if (error instanceof ScraperError) return error;
  const message = error instanceof Error ? error.message : String(error);
  return new ScraperError(fallbackCode, message);
}
